### ISSUE TITLE
RU1:Añadir botón para activar visualización de videos

### ISSUE THREAD

**Issue by lgsilvestre** [lgsilvestre/LoboBrowser#2]
**Descripción RU1:** 
Descripción: Aqui se describe el requisito 
Prioridad: Alta
Usuarios: Estudiantes
Fuente: Profesor/Auxiliar

**Modo de uso:** 
Uso RU1 #11 

**Requisitos de Software**
Luis y Romain
- [ ] Iteracion 1
  - [ ] RS1: Añadir JButton en Toolbar. https://github.com/lsilvestre/LoboBrowser/issues/1
  - [ ] RS2: El botón debe tener el mismo aspecto que los demás.   https://github.com/lsilvestre/LoboBrowser/issues/3
  - [ ] Bug: Bug al compilar https://github.com/lsilvestre/LoboBrowser/issues/6
- [ ] Iteracion 2  
  - [ ] bugs #6
  - [ ] RS3:
  - [ ] RS4:
